import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('ðŸŒ± Seeding database...')

  // â”€â”€ Clean up stale products so SKU unique constraints don't conflict â”€â”€
  await prisma.inventory.deleteMany({})
  await prisma.orderItem.deleteMany({})
  await prisma.product.deleteMany({})
  console.log('ðŸ§¹ Old products cleared')

  // â”€â”€ Delivery Zones â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const zones = await Promise.all([
    prisma.deliveryZone.upsert({
      where: { id: 'zone-woodlawn' },
      update: {},
      create: {
        id: 'zone-woodlawn',
        name: 'Woodlawn / Hyde Park (Immediate)',
        zipCodes: ['60637', '60615', '60619', '60649'],
        minOrderAmount: 2000,
        deliveryFee: 399,
        freeDeliveryThreshold: 5000,
        estimatedMinutesMin: 45,
        estimatedMinutesMax: 75,
        sortOrder: 1,
      },
    }),
    prisma.deliveryZone.upsert({
      where: { id: 'zone-south-side' },
      update: {},
      create: {
        id: 'zone-south-side',
        name: 'South Side Extended',
        zipCodes: ['60620', '60621', '60628', '60636', '60652', '60653'],
        minOrderAmount: 2500,
        deliveryFee: 599,
        freeDeliveryThreshold: 7500,
        estimatedMinutesMin: 60,
        estimatedMinutesMax: 90,
        sortOrder: 2,
      },
    }),
    prisma.deliveryZone.upsert({
      where: { id: 'zone-greater-chicago' },
      update: {},
      create: {
        id: 'zone-greater-chicago',
        name: 'Greater Chicago',
        zipCodes: ['60601','60602','60603','60604','60605','60606','60607','60608','60609','60610','60611','60612','60613','60614','60616','60617','60618','60622','60623','60624','60625','60626','60629','60630','60631','60632','60633','60634','60638','60639','60640','60641','60642','60643','60644','60645','60646','60647','60648','60651'],
        minOrderAmount: 3500,
        deliveryFee: 899,
        freeDeliveryThreshold: 10000,
        estimatedMinutesMin: 90,
        estimatedMinutesMax: 120,
        sortOrder: 3,
      },
    }),
  ])
  console.log(`âœ… ${zones.length} delivery zones seeded`)

  // â”€â”€ Categories â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const [catStaples, catFrozen, catMeat, catSpices, catDrinks, catProduce, catBeauty] = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'african-staples' },
      update: { imageUrl: '/images/staples/Neat_fufu.jpg' },
      create: { name: 'African Staples', slug: 'african-staples', description: 'Authentic grains, flours, and pantry essentials from across Africa', imageUrl: '/images/staples/Neat_fufu.jpg', sortOrder: 1 },
    }),
    prisma.category.upsert({
      where: { slug: 'frozen-foods' },
      update: { imageUrl: '/images/frozen_foods/salmon.jpg' },
      create: { name: 'Frozen Foods', slug: 'frozen-foods', description: 'Quality frozen meats, fish, and prepared African dishes', imageUrl: '/images/frozen_foods/salmon.jpg', sortOrder: 2 },
    }),
    prisma.category.upsert({
      where: { slug: 'meat-seafood' },
      update: { imageUrl: '/images/meat_seafoods/beef.jpg' },
      create: { name: 'Meat & Seafood', slug: 'meat-seafood', description: 'Fresh and smoked meats, dried fish, and seafood', imageUrl: '/images/meat_seafoods/beef.jpg', sortOrder: 3 },
    }),
    prisma.category.upsert({
      where: { slug: 'spices-seasonings' },
      update: { imageUrl: '/images/spices_seasoning/Jollof_seasoning.jpg' },
      create: { name: 'Spices & Seasonings', slug: 'spices-seasonings', description: 'Authentic African spices, bouillons, and seasoning blends', imageUrl: '/images/spices_seasoning/Jollof_seasoning.jpg', sortOrder: 4 },
    }),
    prisma.category.upsert({
      where: { slug: 'drinks-snacks' },
      update: { imageUrl: '/images/drinks_snacks/Malta-Guinness.png' },
      create: { name: 'Drinks & Snacks', slug: 'drinks-snacks', description: 'African beverages, soft drinks, biscuits, and snacks', imageUrl: '/images/drinks_snacks/Malta-Guinness.png', sortOrder: 5 },
    }),
    prisma.category.upsert({
      where: { slug: 'fresh-produce' },
      update: { imageUrl: '/images/fresh_produce/Ghana_yam.jpg' },
      create: { name: 'Fresh Produce', slug: 'fresh-produce', description: 'Fresh vegetables, plantains, yams, and tropical fruits', imageUrl: '/images/fresh_produce/Ghana_yam.jpg', sortOrder: 6 },
    }),
    prisma.category.upsert({
      where: { slug: 'beauty-care' },
      update: { imageUrl: '/images/beauty_care/Epiderm_Cream.jpg' },
      create: { name: 'Beauty & Care', slug: 'beauty-care', description: 'Skincare, hygiene, and health products popular across Africa', imageUrl: '/images/beauty_care/Epiderm_Cream.jpg', sortOrder: 7 },
    }),
  ])
  console.log('âœ… 7 categories seeded')

  // â”€â”€ Products â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const products = await Promise.all([

    // â”€â”€ STAPLES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'egusi-melon-seed-500g' },
      update: { images: [{ url: '/images/spices_seasoning/egusi.jpg', alt: 'Egusi Melon Seed 500g', position: 0 }] },
      create: {
        name: 'Egusi Melon Seed 500g',
        slug: 'egusi-melon-seed-500g',
        description: 'Premium ground egusi melon seeds, perfect for soups and stews. Sourced directly from West Africa.',
        shortDescription: 'Premium ground egusi for authentic West African soups',
        categoryId: catStaples.id,
        price: 1299,
        compareAtPrice: 1499,
        sku: 'EGU-500-GND',
        weight: 1.1, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/egusi.jpg', alt: 'Egusi Melon Seed 500g', position: 0 }],
        tags: ['egusi', 'soup', 'nigerian', 'ghanaian', 'west-african'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 48, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'cassava-flour-fufu-2kg' },
      update: { images: [{ url: '/images/staples/Neat_fufu.jpg', alt: 'Cassava Flour (Fufu) 2kg', position: 0 }] },
      create: {
        name: 'Cassava Flour (Fufu) 2kg',
        slug: 'cassava-flour-fufu-2kg',
        description: 'Smooth cassava flour for making fufu, eba, and other West African swallows. Light and quick to prepare.',
        shortDescription: 'Smooth cassava flour for fufu and swallows',
        categoryId: catStaples.id,
        price: 1099,
        sku: 'CAS-FLR-2KG',
        weight: 4.4, weightUnit: 'LB',
        images: [{ url: '/images/staples/Neat_fufu.jpg', alt: 'Cassava Flour (Fufu) 2kg', position: 0 }],
        tags: ['cassava', 'fufu', 'eba', 'swallow', 'nigerian', 'ghanaian'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 55, lowStockThreshold: 10 } },
      },
    }),

    // â”€â”€ FROZEN FOODS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'frozen-salmon-fillet' },
      update: { images: [{ url: '/images/frozen_foods/salmon.jpg', alt: 'Frozen Salmon Fillet', position: 0 }] },
      create: {
        name: 'Frozen Salmon Fillet',
        slug: 'frozen-salmon-fillet',
        description: 'Premium frozen Atlantic salmon fillets. Rich in omega-3 fatty acids, perfect for grilling, baking, or frying.',
        shortDescription: 'Premium frozen Atlantic salmon fillets',
        categoryId: catFrozen.id,
        price: 1499,
        sku: 'FRZ-SAL-FLT',
        weight: 2.0, weightUnit: 'LB',
        images: [{ url: '/images/frozen_foods/salmon.jpg', alt: 'Frozen Salmon Fillet', position: 0 }],
        tags: ['salmon', 'fish', 'frozen', 'seafood'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 30, lowStockThreshold: 8 } },
      },
    }),

    // â”€â”€ MEAT & SEAFOOD â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'beef-chunks' },
      update: { images: [{ url: '/images/meat_seafoods/beef.jpg', alt: 'Beef Chunks', position: 0 }] },
      create: {
        name: 'Beef Chunks (per lb)',
        slug: 'beef-chunks',
        description: 'Fresh beef chunks, ideal for Nigerian stews, pepper soup, and African soups. Cut to order.',
        shortDescription: 'Fresh beef chunks for African stews and soups',
        categoryId: catMeat.id,
        price: 1299,
        sku: 'MT-BEEF-LB',
        weight: 1.0, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/beef.jpg', alt: 'Beef Chunks', position: 0 }],
        tags: ['beef', 'meat', 'nigerian', 'stew'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 40, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'goat-meat-per-lb' },
      update: { images: [{ url: '/images/meat_seafoods/goatmeat.jpg', alt: 'Goat Meat', position: 0 }] },
      create: {
        name: 'Goat Meat (per lb)',
        slug: 'goat-meat-per-lb',
        description: 'Fresh goat meat, perfect for pepper soup, asun, and various West African delicacies.',
        shortDescription: 'Fresh goat meat for pepper soup and asun',
        categoryId: catMeat.id,
        price: 1599,
        sku: 'MT-GOAT-LB',
        weight: 1.0, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/goatmeat.jpg', alt: 'Goat Meat', position: 0 }],
        tags: ['goat', 'meat', 'pepper-soup', 'asun', 'nigerian'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 25, lowStockThreshold: 6 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'catfish-whole' },
      update: { images: [{ url: '/images/meat_seafoods/catfish.jpg', alt: 'Whole Catfish', position: 0 }] },
      create: {
        name: 'Whole Catfish (per lb)',
        slug: 'catfish-whole',
        description: 'Fresh whole catfish, great for catfish pepper soup, catfish stew, and grilling.',
        shortDescription: 'Fresh whole catfish for pepper soup and stew',
        categoryId: catMeat.id,
        price: 999,
        sku: 'SF-CATFISH-LB',
        weight: 1.0, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/catfish.jpg', alt: 'Whole Catfish', position: 0 }],
        tags: ['catfish', 'fish', 'pepper-soup', 'nigerian'],
        isActive: true,
        inventory: { create: { quantity: 20, lowStockThreshold: 5 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'cowskin-ponmo' },
      update: { images: [{ url: '/images/meat_seafoods/cowskin.jpg', alt: 'Cowskin (Ponmo)', position: 0 }] },
      create: {
        name: 'Cowskin (Ponmo)',
        slug: 'cowskin-ponmo',
        description: 'Soft cooked cowskin (ponmo), a West African delicacy used in soups, stews, and as a protein-rich side.',
        shortDescription: 'Cooked cowskin (ponmo) for soups and stews',
        categoryId: catMeat.id,
        price: 499,
        sku: 'MT-PONMO',
        weight: 0.5, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/cowskin.jpg', alt: 'Cowskin (Ponmo)', position: 0 }],
        tags: ['ponmo', 'cowskin', 'nigerian', 'soup'],
        isActive: true,
        inventory: { create: { quantity: 35, lowStockThreshold: 8 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ground-crayfish-200g' },
      update: { images: [{ url: '/images/meat_seafoods/crayfish.jpg', alt: 'Ground Crayfish 200g', position: 0 }] },
      create: {
        name: 'Ground Crayfish 200g',
        slug: 'ground-crayfish-200g',
        description: 'Premium ground dried crayfish, essential seasoning for Nigerian and Cameroonian soups and stews.',
        shortDescription: 'Premium ground dried crayfish for authentic Nigerian cooking',
        categoryId: catMeat.id,
        price: 699,
        sku: 'CRY-GND-200G',
        weight: 0.44, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/crayfish.jpg', alt: 'Ground Crayfish 200g', position: 0 }],
        tags: ['crayfish', 'seafood', 'seasoning', 'nigerian'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 28, lowStockThreshold: 6 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'azu-dried-fish' },
      update: { images: [{ url: '/images/meat_seafoods/Azu.jpg', alt: 'Azu Dried Fish', position: 0 }] },
      create: {
        name: 'Azu Dried Fish',
        slug: 'azu-dried-fish',
        description: 'Authentic sun-dried stockfish (Azu), a staple ingredient in Igbo and Eastern Nigerian soups like Ofe Onugbu and Oha.',
        shortDescription: 'Sun-dried stockfish for traditional Igbo soups',
        categoryId: catMeat.id,
        price: 799,
        sku: 'SF-AZU-DRY',
        weight: 0.5, weightUnit: 'LB',
        images: [{ url: '/images/meat_seafoods/Azu.jpg', alt: 'Azu Dried Fish', position: 0 }],
        tags: ['azu', 'stockfish', 'dried-fish', 'igbo', 'nigerian'],
        isActive: true,
        inventory: { create: { quantity: 22, lowStockThreshold: 5 } },
      },
    }),

    // â”€â”€ SPICES & SEASONINGS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'jollof-seasoning' },
      update: { images: [{ url: '/images/spices_seasoning/Jollof_seasoning.jpg', alt: 'Jollof Seasoning', position: 0 }] },
      create: {
        name: 'Jollof Seasoning Blend',
        slug: 'jollof-seasoning',
        description: 'The perfect all-in-one seasoning blend for authentic Jollof rice. Perfectly balanced with tomatoes, peppers, and spices.',
        shortDescription: 'All-in-one blend for perfect Jollof rice every time',
        categoryId: catSpices.id,
        price: 449,
        sku: 'SPC-JOLLOF',
        weight: 0.3, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/Jollof_seasoning.jpg', alt: 'Jollof Seasoning', position: 0 }],
        tags: ['jollof', 'seasoning', 'rice', 'nigerian', 'ghanaian'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 60, lowStockThreshold: 12 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'wonda-curry-powder' },
      update: { images: [{ url: '/images/spices_seasoning/Wonda_curry.jpg', alt: 'Wonda Curry Powder', position: 0 }] },
      create: {
        name: 'Wonda Curry Powder',
        slug: 'wonda-curry-powder',
        description: 'Aromatic curry powder blend popular in West African cooking. Great for stews, rice, and grilled meats.',
        shortDescription: 'Aromatic West African curry powder',
        categoryId: catSpices.id,
        price: 399,
        sku: 'SPC-CURRY-WND',
        weight: 0.25, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/Wonda_curry.jpg', alt: 'Wonda Curry Powder', position: 0 }],
        tags: ['curry', 'seasoning', 'spice', 'west-african'],
        isActive: true,
        inventory: { create: { quantity: 45, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'benny-stock-cubes' },
      update: { images: [{ url: '/images/spices_seasoning/Benny_Stock.jpg', alt: 'Benny Stock Cubes', position: 0 }] },
      create: {
        name: 'Benny Stock Cubes',
        slug: 'benny-stock-cubes',
        description: 'Rich and flavourful stock cubes beloved across West Africa. Adds deep umami to soups, stews, and rice dishes.',
        shortDescription: 'Rich stock cubes for deep flavour in any dish',
        categoryId: catSpices.id,
        price: 299,
        sku: 'SPC-BENNY-STK',
        weight: 0.2, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/Benny_Stock.jpg', alt: 'Benny Stock Cubes', position: 0 }],
        tags: ['stock-cube', 'bouillon', 'seasoning', 'nigerian'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 80, lowStockThreshold: 15 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'bay-leaf' },
      update: { images: [{ url: '/images/spices_seasoning/Bayleaf.jpg', alt: 'Bay Leaf', position: 0 }] },
      create: {
        name: 'Bay Leaf (Dried)',
        slug: 'bay-leaf',
        description: 'Aromatic dried bay leaves for soups, stews, and rice. Adds a subtle herbal depth to any African or Caribbean dish.',
        shortDescription: 'Dried bay leaves for soups and stews',
        categoryId: catSpices.id,
        price: 249,
        sku: 'SPC-BAYLEAF',
        weight: 0.1, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/Bayleaf.jpg', alt: 'Bay Leaf', position: 0 }],
        tags: ['bay-leaf', 'herb', 'spice', 'soup'],
        isActive: true,
        inventory: { create: { quantity: 50, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'bonnet-pepper' },
      update: { images: [{ url: '/images/spices_seasoning/Bonnet Pepper.jpg', alt: 'Bonnet Pepper', position: 0 }] },
      create: {
        name: 'Bonnet Pepper (Scotch Bonnet)',
        slug: 'bonnet-pepper',
        description: 'Fresh scotch bonnet peppers â€” the backbone of West African pepper soups, stews, and hot sauces. Handle with care!',
        shortDescription: 'Fiery scotch bonnet peppers for authentic heat',
        categoryId: catSpices.id,
        price: 349,
        sku: 'SPC-BONNET',
        weight: 0.3, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/Bonnet%20Pepper.jpg', alt: 'Bonnet Pepper', position: 0 }],
        tags: ['scotch-bonnet', 'pepper', 'hot', 'nigerian', 'ghanaian'],
        isActive: true,
        inventory: { create: { quantity: 40, lowStockThreshold: 8 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ground-pepper' },
      update: { images: [{ url: '/images/spices_seasoning/pepper.jpg', alt: 'Ground Pepper', position: 0 }] },
      create: {
        name: 'Ground Pepper Blend',
        slug: 'ground-pepper',
        description: 'A finely ground blend of African peppers for soups, stews, and marinades. Adds warmth without overwhelming heat.',
        shortDescription: 'Finely ground African pepper blend',
        categoryId: catSpices.id,
        price: 299,
        sku: 'SPC-PEPPER-GND',
        weight: 0.25, weightUnit: 'LB',
        images: [{ url: '/images/spices_seasoning/pepper.jpg', alt: 'Ground Pepper', position: 0 }],
        tags: ['pepper', 'spice', 'ground', 'seasoning'],
        isActive: true,
        inventory: { create: { quantity: 55, lowStockThreshold: 10 } },
      },
    }),

    // â”€â”€ DRINKS & SNACKS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'malta-guinness-330ml' },
      update: { images: [{ url: '/images/drinks_snacks/Malta-Guinness.png', alt: 'Malta Guinness 330ml', position: 0 }] },
      create: {
        name: 'Malta Guinness 330ml',
        slug: 'malta-guinness-330ml',
        description: 'The iconic non-alcoholic malt drink from Nigeria. Rich, sweet and nutritious â€” loved across Africa and the diaspora.',
        shortDescription: 'Iconic Nigerian non-alcoholic malt drink',
        categoryId: catDrinks.id,
        price: 249,
        sku: 'DRK-MALTA-330',
        weight: 0.75, weightUnit: 'LB',
        images: [{ url: '/images/drinks_snacks/Malta-Guinness.png', alt: 'Malta Guinness 330ml', position: 0 }],
        tags: ['malta', 'malt', 'drink', 'nigerian', 'non-alcoholic'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 100, lowStockThreshold: 20 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: '7up-350ml' },
      update: { images: [{ url: '/images/drinks_snacks/7up.jpg', alt: '7UP 350ml', position: 0 }] },
      create: {
        name: '7UP 350ml',
        slug: '7up-350ml',
        description: 'Crisp and refreshing lemon-lime soda. A household favourite across Nigeria and West Africa.',
        shortDescription: 'Refreshing lemon-lime soda',
        categoryId: catDrinks.id,
        price: 199,
        sku: 'DRK-7UP-350',
        weight: 0.75, weightUnit: 'LB',
        images: [{ url: '/images/drinks_snacks/7up.jpg', alt: '7UP 350ml', position: 0 }],
        tags: ['7up', 'soda', 'drink', 'soft-drink'],
        isActive: true,
        inventory: { create: { quantity: 120, lowStockThreshold: 24 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'milo-chocolate-drink-400g' },
      update: { images: [{ url: '/images/drinks_snacks/Milo.jpg', alt: 'Milo Chocolate Drink 400g', position: 0 }] },
      create: {
        name: 'Milo Chocolate Drink 400g',
        slug: 'milo-chocolate-drink-400g',
        description: 'The classic NestlÃ© Milo chocolate and malt energy drink, popular across Africa. Great hot or cold.',
        shortDescription: 'Classic Milo chocolate malt energy drink powder',
        categoryId: catDrinks.id,
        price: 899,
        sku: 'DRK-MILO-400',
        weight: 0.9, weightUnit: 'LB',
        images: [{ url: '/images/drinks_snacks/Milo.jpg', alt: 'Milo Chocolate Drink 400g', position: 0 }],
        tags: ['milo', 'chocolate', 'malt', 'drink', 'nestle'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 60, lowStockThreshold: 12 } },
      },
    }),

    // â”€â”€ FRESH PRODUCE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'ghana-yam' },
      update: { images: [{ url: '/images/fresh_produce/Ghana_yam.jpg', alt: 'Ghana Yam', position: 0 }] },
      create: {
        name: 'Ghana Yam (per lb)',
        slug: 'ghana-yam',
        description: 'Premium Ghana yam, perfect for pounded yam, boiled yam, yam porridge, and yam fries. Starchy and delicious.',
        shortDescription: 'Premium Ghana yam for pounded yam and porridge',
        categoryId: catProduce.id,
        price: 599,
        sku: 'PRD-YAM-GH',
        weight: 1.0, weightUnit: 'LB',
        images: [{ url: '/images/fresh_produce/Ghana_yam.jpg', alt: 'Ghana Yam', position: 0 }],
        tags: ['yam', 'ghana', 'pounded-yam', 'fresh-produce'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 50, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'unripe-plantain' },
      update: { images: [{ url: '/images/fresh_produce/unriped_plantain.jpg', alt: 'Unripe Plantain', position: 0 }] },
      create: {
        name: 'Unripe Plantain (per lb)',
        slug: 'unripe-plantain',
        description: 'Fresh unripe plantain for boli, plantain chips, and African plantain stew. Firm and starchy.',
        shortDescription: 'Fresh unripe plantain for boli and chips',
        categoryId: catProduce.id,
        price: 349,
        sku: 'PRD-PLANTAIN-GR',
        weight: 1.0, weightUnit: 'LB',
        images: [{ url: '/images/fresh_produce/unriped_plantain.jpg', alt: 'Unripe Plantain', position: 0 }],
        tags: ['plantain', 'boli', 'fresh-produce', 'nigerian'],
        isActive: true,
        inventory: { create: { quantity: 60, lowStockThreshold: 12 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'eggplant-garden-egg' },
      update: { images: [{ url: '/images/fresh_produce/eggplant.jpg', alt: 'Eggplant (Garden Egg)', position: 0 }] },
      create: {
        name: 'Eggplant / Garden Egg',
        slug: 'eggplant-garden-egg',
        description: 'Fresh garden eggs (eggplant) used in African garden egg stew, sauce, and as a healthy snack with groundnut paste.',
        shortDescription: 'Fresh garden eggs for stew and garden egg sauce',
        categoryId: catProduce.id,
        price: 299,
        sku: 'PRD-GARDEN-EGG',
        weight: 0.5, weightUnit: 'LB',
        images: [{ url: '/images/fresh_produce/eggplant.jpg', alt: 'Eggplant (Garden Egg)', position: 0 }],
        tags: ['eggplant', 'garden-egg', 'fresh-produce', 'nigerian'],
        isActive: true,
        inventory: { create: { quantity: 40, lowStockThreshold: 8 } },
      },
    }),

    // â”€â”€ BEAUTY & CARE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    prisma.product.upsert({
      where: { slug: 'epiderm-cream' },
      update: { images: [{ url: '/images/beauty_care/Epiderm_Cream.jpg', alt: 'Epiderm Cream', position: 0 }] },
      create: {
        name: 'Epiderm Cream',
        slug: 'epiderm-cream',
        description: 'Popular multi-purpose skin cream widely used across West Africa for smooth, even-toned skin.',
        shortDescription: 'Multi-purpose skin cream for smooth even skin',
        categoryId: catBeauty.id,
        price: 899,
        sku: 'BEA-EPIDERM',
        weight: 0.3, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Epiderm_Cream.jpg', alt: 'Epiderm Cream', position: 0 }],
        tags: ['cream', 'skincare', 'beauty', 'african'],
        isActive: true, isFeatured: true,
        inventory: { create: { quantity: 35, lowStockThreshold: 7 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'carotone-cream' },
      update: { images: [{ url: '/images/beauty_care/Carotone.jpg', alt: 'Carotone Cream', position: 0 }] },
      create: {
        name: 'Carotone Brightening Cream',
        slug: 'carotone-cream',
        description: 'Carotone brightening cream enriched with carrot oil and vitamin E for a radiant, even complexion.',
        shortDescription: 'Carrot oil brightening cream for radiant skin',
        categoryId: catBeauty.id,
        price: 799,
        sku: 'BEA-CAROTONE',
        weight: 0.3, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Carotone.jpg', alt: 'Carotone Cream', position: 0 }],
        tags: ['carotone', 'cream', 'skincare', 'brightening'],
        isActive: true,
        inventory: { create: { quantity: 28, lowStockThreshold: 6 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'dettol-disinfectant' },
      update: { images: [{ url: '/images/beauty_care/Detol_disinfectant.jpg', alt: 'Dettol Disinfectant', position: 0 }] },
      create: {
        name: 'Dettol Disinfectant Liquid',
        slug: 'dettol-disinfectant',
        description: 'Trusted antibacterial disinfectant liquid. Kills 99.9% of germs. Use for bathing, cleaning, and laundry.',
        shortDescription: 'Trusted antibacterial disinfectant â€” kills 99.9% of germs',
        categoryId: catBeauty.id,
        price: 599,
        sku: 'HYG-DETTOL-DIS',
        weight: 0.75, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Detol_disinfectant.jpg', alt: 'Dettol Disinfectant', position: 0 }],
        tags: ['dettol', 'disinfectant', 'hygiene', 'antibacterial'],
        isActive: true,
        inventory: { create: { quantity: 50, lowStockThreshold: 10 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'dettol-soap' },
      update: { images: [{ url: '/images/beauty_care/Detol_soap.jpg', alt: 'Dettol Soap', position: 0 }] },
      create: {
        name: 'Dettol Antibacterial Soap',
        slug: 'dettol-soap',
        description: 'Dettol antibacterial bar soap. Provides 12-hour protection against bacteria for clean, healthy skin.',
        shortDescription: 'Antibacterial bar soap with 12-hour protection',
        categoryId: catBeauty.id,
        price: 399,
        sku: 'HYG-DETTOL-SOAP',
        weight: 0.2, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Detol_soap.jpg', alt: 'Dettol Soap', position: 0 }],
        tags: ['dettol', 'soap', 'hygiene', 'antibacterial'],
        isActive: true,
        inventory: { create: { quantity: 70, lowStockThreshold: 15 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'dynewell-syrup' },
      update: { images: [{ url: '/images/beauty_care/Dynewell.jpg', alt: 'Dynewell Syrup', position: 0 }] },
      create: {
        name: 'Dynewell Appetite Syrup',
        slug: 'dynewell-syrup',
        description: 'Dynewell vitamin and appetite stimulant syrup. Supports healthy weight gain and appetite in adults and children.',
        shortDescription: 'Vitamin syrup to support appetite and healthy weight',
        categoryId: catBeauty.id,
        price: 1299,
        sku: 'HLT-DYNEWELL',
        weight: 0.5, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Dynewell.jpg', alt: 'Dynewell Syrup', position: 0 }],
        tags: ['dynewell', 'vitamin', 'health', 'appetite'],
        isActive: true,
        inventory: { create: { quantity: 20, lowStockThreshold: 5 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'funbact-cream' },
      update: { images: [{ url: '/images/beauty_care/Funbact.jpg', alt: 'Funbact Cream', position: 0 }] },
      create: {
        name: 'Funbact-A Triple Action Cream',
        slug: 'funbact-cream',
        description: 'Funbact-A triple action cream for fungal skin infections, eczema, and inflammatory skin conditions.',
        shortDescription: 'Triple action cream for skin infections and eczema',
        categoryId: catBeauty.id,
        price: 699,
        sku: 'HLT-FUNBACT',
        weight: 0.15, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Funbact.jpg', alt: 'Funbact Cream', position: 0 }],
        tags: ['funbact', 'cream', 'skin', 'health', 'antifungal'],
        isActive: true,
        inventory: { create: { quantity: 30, lowStockThreshold: 6 } },
      },
    }),
    prisma.product.upsert({
      where: { slug: 'bath-sponge' },
      update: { images: [{ url: '/images/beauty_care/Sponge.jpg', alt: 'Bath Sponge', position: 0 }] },
      create: {
        name: 'African Bath Sponge',
        slug: 'bath-sponge',
        description: 'Durable African net bath sponge. Creates a rich lather and exfoliates the skin for a deep clean.',
        shortDescription: 'Durable African net sponge for a deep clean',
        categoryId: catBeauty.id,
        price: 199,
        sku: 'HYG-SPONGE',
        weight: 0.1, weightUnit: 'LB',
        images: [{ url: '/images/beauty_care/Sponge.jpg', alt: 'Bath Sponge', position: 0 }],
        tags: ['sponge', 'bath', 'hygiene', 'exfoliate'],
        isActive: true,
        inventory: { create: { quantity: 100, lowStockThreshold: 20 } },
      },
    }),
  ])
  console.log(`âœ… ${products.length} products seeded`)

  // â”€â”€ Coupons â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await prisma.coupon.upsert({
    where: { code: 'WELCOME10' },
    update: {},
    create: {
      code: 'WELCOME10',
      description: '10% off your first order',
      type: 'PERCENTAGE',
      value: 1000,
      minOrderAmount: 2000,
      usesPerCustomer: 1,
      isActive: true,
    },
  })
  await prisma.coupon.upsert({
    where: { code: 'FREEDEL' },
    update: {},
    create: {
      code: 'FREEDEL',
      description: 'Free delivery on any order',
      type: 'FREE_SHIPPING',
      value: 0,
      minOrderAmount: 1500,
      maxUses: 100,
      usesPerCustomer: 1,
      isActive: true,
    },
  })
  console.log('âœ… Coupons seeded')

  console.log('ðŸŽ‰ Database seeded successfully!')
}

main()
  .catch((e) => { console.error('âŒ Seed error:', e); process.exit(1) })
  .finally(() => prisma.$disconnect())

